### ISSUE TITLE
Document history results format better

### ISSUE THREAD

**Issue by lightserve** [nas/yahoo_stock#3]
It would be helpful to add to the readme the format for history results, as it confused me for a while.  

ruby-1.9.2-p180 :006 > history.results
 => #<YahooStock::Result:0x00000103d5e400 @context="2011-02-25,16.39,16.77,16.38,16.50,16402400,16.50\n2011-02-24,16.66,16.73,16.04,16.37,31528900,16.37\n"> 
ruby-1.9.2-p180 :007 > history.values_with_header
 => "Date,Open,High,Low,Close,Volume,Adj Close\n2011-02-25,16.39,16.77,16.38,16.50,16402400,16.50\n2011-02-24,16.66,16.73,16.04,16.37,31528900,16.37\n" 

E.g. it is not obvious that every day's results will be formatted as 4 values.  I was confused because I thought I would get 1 value for each day.  Also, the history.values_with_header method is not featured in the readme.  Just some suggestions -- great gem, thanks.

**Comment by nas** [comment]
[Closed by e7e6ae2f4c3856c9c5545a3137e014ef73b50f15] Update readme to elaborate on history object.
